/// Flutter icons SocialsIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SocialsIcons
///      fonts:
///       - asset: fonts/SocialsIcons.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
// ignore_for_file: public_member_api_docs, constant_identifier_names

import 'package:flutter/widgets.dart';

/// The icons class that provides icons for supported platforms
class SocialsIcons {
  SocialsIcons._();

  static const String _kFontFam = 'SocialsIcons';

  static const IconData twitter = IconData(0xf099, fontFamily: _kFontFam);
  static const IconData facebook = IconData(0xf09a, fontFamily: _kFontFam);
  static const IconData pinterest = IconData(0xf0d2, fontFamily: _kFontFam);
  static const IconData instagram = IconData(0xf16d, fontFamily: _kFontFam);
  static const IconData wechat = IconData(0xf1d7, fontFamily: _kFontFam);
  static const IconData whatsapp = IconData(0xf232, fontFamily: _kFontFam);
  static const IconData reddit_alien = IconData(0xf281, fontFamily: _kFontFam);
  static const IconData snapchat_ghost = IconData(0xf2ac, fontFamily: _kFontFam);
  static const IconData line = IconData(0xf3c0, fontFamily: _kFontFam);
  static const IconData telegram_plane = IconData(0xf3fe, fontFamily: _kFontFam);
  static const IconData viber = IconData(0xf409, fontFamily: _kFontFam);
}
