// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAizp2ZGAAQxGfq4KMDWB3y8clHk9N5sfw",
      authDomain: "playcrypto365app.firebaseapp.com",
      projectId: "playcrypto365app",
      storageBucket: "playcrypto365app.firebasestorage.app",
      messagingSenderId: "827793044377",
      appId: "1:827793044377:web:46059e79b8dcb44e695908",
      measurementId: "G-V3SJWTFTSM");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkMvVL4T11dBH6o7VKE8-AUYQceTk8Zek',
    appId: '1:827793044377:android:1212598be184dcc6695908',
    messagingSenderId: '827793044377',
    projectId: 'playcrypto365app',
    storageBucket: 'playcrypto365app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkMvVL4T11dBH6o7VKE8-AUYQceTk8Zek',
    appId: '1:827793044377:android:1212598be184dcc6695908',
    messagingSenderId: '827793044377',
    projectId: 'playcrypto365app',
    storageBucket: 'playcrypto365app.firebasestorage.app',
    iosBundleId: 'com.playcrypto365.user',
  );
}
